---
title: "Interactive_map"
author: "Lucas Lu"
date: '2022-04-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(plotly)
library(ggplot2)
library(DMwR2)
library(dplyr)
library(lubridate)
library(hrbrthemes)
```


```{r}
```

```{r}
#setwd("E:/QMSS/DV/Group_V_Global_Temperature/GlobalLandTemperaturesByCountry")
```


```{r}
getwd()
```

```{r}
Country<-read_csv("E:/QMSS/DV/Group_V_Global_Temperature/GlobalLandTemperaturesByCountry.csv")
```
```{r}
class(Country$dt)
```

```{r}
New_Country<-Country%>%
  filter(AverageTemperature!="N/A"& AverageTemperatureUncertainty!="N/A")
```

```{r}
New_Country<-New_Country%>%
  filter(dt >="1970-01-01")
```

```{r}
New_Country<-New_Country %>%
    group_by(Country) %>%
  
    mutate(Diff_Temp = AverageTemperature - lag(AverageTemperature,12))
```






```{r}
USA<-New_Country%>%
  filter(Country %in% c("United States"))
```

```{r}
class(USA$dt)
```
```{r}
Japan<-New_Country%>%
  filter(Country %in% c("Japan"))
```

```{r}
Russia<-New_Country%>%
  filter(Country %in% c("Russia"))
```


```{r}
plot1<- ggplot() +
    geom_line(data = Russia, aes(x=dt, y=AverageTemperature,color="AverageTemperature")) +
    geom_line(data = Russia, aes(x=dt, y=Diff_Temp,color="Diff_Temp"))+
    xlab("Dates")+
    ylab("Tempt")+
   labs(color="Tempt_Type")+
    ggtitle("Russia Monthly Temperature and Difference with previous year from 1990 to 2013")+
    scale_x_date(limit=c(as.Date("1990-01-01"),as.Date("2013-09-11")))+
   theme_minimal()

  
ggplotly(plot1)
#plot1
```

```{r}
plot2<-ggplot()+
    geom_line(data = USA, aes(x=dt, y=AverageTemperature,color="AverageTemperature")) +
    geom_line(data = USA, aes(x=dt, y=Diff_Temp,color="Diff_Temp"))+
    xlab("Dates")+
    ylab("Tempt")+
   labs(color="Tempt_Type")+
  ggtitle("USA Monthly Temperature and Difference with previous year from 1990 to 2013")+
    scale_x_date(limit=c(as.Date("1990-01-01"),as.Date("2013-09-11")))+
   theme_minimal()
ggplotly(plot2)
```


```{r}
plot3<-ggplot()+
    geom_line(data = Japan, aes(x=dt, y=AverageTemperature,color="AverageTemperature")) +
    geom_line(data = Japan, aes(x=dt, y=Diff_Temp,color="Diff_Temp"))+
    xlab("Dates")+
    ylab("Tempt")+
   ggtitle("Japan Monthly Temperature and Difference with previous year from 1990 to 2013")+
   labs(color="Tempt_Type")+
    scale_x_date(limit=c(as.Date("1990-01-01"),as.Date("2013-09-11")))+
   theme_minimal()
ggplotly(plot3)

```



```{r}
avg_diff<-New_Country%>%
  group_by(Country)%>%
  summarise(Variance = var(AverageTemperature))%>%
  arrange(Variance)  %>%
  mutate(rank = row_number())%>%
  filter(rank<=10)
  
```

```{r}
class(New_Country$Diff_Temp)
```


```{r}
avg_diff_by_tempdiff<-New_Country%>%
  filter(Diff_Temp!="N/A")%>%
  group_by(Country)%>%
  summarise(meanD = mean(Diff_Temp))

```


```{r}
Singapore<-New_Country%>%
  filter(Country %in% c("Singapore"))
  
```


```{r}
plot4<-ggplot()+
    geom_line(data = Singapore, aes(x=dt, y=AverageTemperature,color="AverageTemperature")) +
    geom_line(data = Singapore, aes(x=dt, y=Diff_Temp,color="Diff_Temp"))+
    xlab("Dates")+
    ylab("Tempt")+
   labs(color="Tempt_Type")+
   ggtitle("Singapore Monthly Temperature and Difference with previous year from 1990 to 2013")+
    scale_x_date(limit=c(as.Date("1971-01-01"),as.Date("2013-09-11")))+
   theme_minimal()
ggplotly(plot4)
```



```{r}
Indonesia<-New_Country%>%
  filter(Country %in% c("Colombia"))
  
```


```{r}
plot4<-ggplot()+
    geom_line(data = Indonesia, aes(x=dt, y=AverageTemperature,color="AverageTemperature")) +
    geom_line(data = Indonesia, aes(x=dt, y=Diff_Temp,color="Diff_Temp"))+
    xlab("Dates")+
    ylab("Tempt")+
   labs(color="Tempt_Type")+
   ggtitle("Columbia Monthly Temperature and Difference with previous year from 1990 to 2013")+
    scale_x_date(limit=c(as.Date("1971-01-01"),as.Date("2013-09-11")))+
   theme_minimal()
ggplotly(plot4)
```


```{r}

By_Year<-New_Country%>%
  mutate(year = substring(dt,0,4))%>%
  group_by(Country,year)%>%
  summarise(Year_Tempt = mean(AverageTemperature))%>%
  mutate(Year_diff = Year_Tempt-lag(Year_Tempt))
  
```
```{r}
By_Year$year<-ymd(By_Year$year, truncated = 2L)
```

```{r}
class(By_Year$year)
```

```{r}
By_Year_USA<-By_Year%>%
  filter(Country %in% c("United States"))
```

```{r}
Year_1<-ggplot()+
    geom_line(data = By_Year_USA, aes(x=year, y=Year_Tempt,color="Year_Tempt")) +
    geom_line(data = By_Year_USA, aes(x=year, y=Year_diff,color="Year_diff"))+
      xlab("Dates")+
    ylab("Tempt")+
   labs(color="Tempt_Type")+
   ggtitle("USA Yearly Temperature and Difference with previous year from 1990 to 2013")+
    scale_x_date(limit=c(as.Date("1971-01-01"),as.Date("2013-09-11")))+
   theme_minimal()
ggplotly(Year_1)
```


```{r}
By_Year_Russia<-By_Year%>%
  filter(Country %in% c("Russia"))
```

```{r}
Year_2<-ggplot()+
    geom_line(data = By_Year_Russia, aes(x=year, y=Year_Tempt,color="Year_Tempt")) +
    geom_line(data = By_Year_Russia, aes(x=year, y=Year_diff,color="Year_diff"))+
      xlab("Dates")+
    ylab("Tempt")+
   labs(color="Tempt_Type")+
   ggtitle("Russia Yearly Temperature and Difference with previous year from 1990 to 2013")+
    scale_x_date(limit=c(as.Date("1971-01-01"),as.Date("2013-09-11")))+
   theme_minimal()
ggplotly(Year_2)
```


```{r}
By_Year_Japan<-By_Year%>%
  filter(Country %in% c("Japan"))
```

```{r}
Year_3<-ggplot()+
    geom_line(data = By_Year_Japan, aes(x=year, y=Year_Tempt,color="Year_Tempt")) +
    geom_line(data = By_Year_Japan, aes(x=year, y=Year_diff,color="Year_diff"))+
      xlab("Dates")+
    ylab("Tempt")+
   labs(color="Tempt_Type")+
   ggtitle("JP Yearly Temperature and Difference with previous year from 1990 to 2013")+
    scale_x_date(limit=c(as.Date("1971-01-01"),as.Date("2013-09-11")))+
   theme_minimal()
ggplotly(Year_3)
```


```{r}
Continents<-New_Country%>%
  filter(Country %in% c("Asia", "Africa", "North America", "South America", "Antarctica", 'Europe','Oceania'))
```

```{r}

Vio_1<-ggplot(data = Continents, aes(x= Country,y=AverageTemperature,fill=Country))+
  geom_violin() +
  geom_boxplot(width=0.1, color="grey", alpha=0.2)+
   theme_minimal()
  
ggplotly(Vio_1)
```

```{r}
library(tidygeocoder)
```
```{r}
#coord <- geo(By_Year$Country)
#write.csv(coord,"E:/QMSS/DV/Group_V_Global_Temperature/coord.csv", row.names = FALSE,fileEncoding = "UTF-8")
```

```{r}
#coord<-read_csv("E:/QMSS/DV/Group_V_Global_Temperature/coord.csv")
```

```{r}
library(rgdal)
```



```{r}
# world_shape = readOGR(dsn= "E:/QMSS/DV/5069/course_content/Lectures/Week07/data/world_map", 
#                      layer="TM_WORLD_BORDERS_SIMPL-0.3")
```

# ```{r}
# By_Year<-By_Year%>%
#   filter(Year_diff!="N/A")
# ```
# 
# ```{r}
# combined <- world_shape@data%>%
#   left_join(By_Year,by = c('NAME' = 'Country'))
# ```
# 
# ```{r}
# Wmerged <-world_shape
# Wmerged@data <- combined
# ```

```{r}
world <- map_data("world") %>%
  filter(region != "Antarctica")
```


```{r}
library(viridis)
library(gganimate)
library(gifski)
```

```{r}
By_year_new <-By_Year%>%
  filter(Year_diff!="N/A")%>%
   right_join(world, by= c("Country" = "region"))%>%
    ggplot(aes(long, lat, 
             group= group, 
             fill= Year_diff)) +
  geom_polygon(color = "white", 
               size = 0.01)+
  theme_void() +
  scale_fill_viridis(option = "B",
                     name= "Year_Diff",
                     guide = guide_colorbar(
                       direction = "horizontal",
                       barheight = unit(2, units = "mm"),
                       barwidth = unit(100, units = "mm"),
                       draw.ulim = FALSE,
                       title.position = "top",
                       title.hjust = 0.5,
                       title.vjust = 0.5 ))+
  labs(title="Yearly Temperature Diff",
       subtitle = "{current_frame}")+
  theme(
    plot.title = element_text(size = 12, hjust = 0.5),
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    plot.caption = element_text(size = 8, hjust = 1),
    legend.position = "bottom") +
  coord_fixed (ratio = 1.3) +
  transition_manual(year)

  
      
```
```{r}
animate(By_year_new, 
        fps = 10, 
        height = 500, 
        width = 700,renderer = gifski_renderer("gganim.gif"),res=200)
```




